### ISSUE TITLE
double-array trie的缺陷

### ISSUE THREAD

**Issue by shenpengjianke** [hanzeil/MassiveStringSearch-Trie#1]
1.无法处理包含型字符串。
比如：先插入bachelor，再插入bache。然后查找bachelor，能找到，查找bache，则找不到。
再比如:先插入bache，再插入bachelor，然后查找bache，找不到。查找bachelor，能找到。

**Comment by shenpengjianke** [comment]
可能是我自身的bug，我再试试。

**Comment by hanzeil** [comment]
这个东西会冲突…不过有解决冲突的方法，可能会复杂，

**Comment by shenpengjianke** [comment]
这个问题，只要把结束符也当成字符，存入trie树中，就可以解决。
